name: SuperLobby
version: ${project.version}
main: com.multocraft.superlobby.SuperLobby
api-version: 1.16
commands:
   delspawn:
      description: delete current spawn
   spawn:
      description: go to spawn
   setspawn:
      description: set a new spawn
   maintenance:
      description: enable or disable maintenance mode
   serverteleport:
      description: teleport to server location
   setserver:
      description: set server teleport location